services:
  app2:
    container_name: 'file-server'
    image: '1596944197/file-server'
    build:
      context: ./
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    ports:
      - '3003:3003'
    volumes:
      - ./file-static:/app/static
    environment:
      NODE_ENV: production
      ALLOW_ORIGIN: http://43.136.58.73
